### PR TITLE
Fix parameter error for LSF GPU tasks

### PR DESCRIPTION
**Pull request by Cloudac7**
For GPU tasks , the positions of two parameters `task_per_node` and `numb_gpu` were written wrongly, causing tasks in PEND state. So here they are corrected. 

Also, the support of `j_exclusive` is added to enable feature that allow a task to run on a card without other tasks submitted even with enough CPU cores available in the queue.

### CODE REVIEW

**Review by AnguseZhang — APPROVED** [review]
Could you please add the documentation in README ?

**Review by njzjz — APPROVED** [review]

**Comment by amcadmus** [comment]
@Cloudac7 an update of the doc is required.

**Comment by Cloudac7** [comment]
> @Cloudac7 an update of the doc is required.

OK. I will give a introduction in the doc.

**Comment by Cloudac7** [comment]
Documentation for added parameters has been added.

**Pull request merged**
