### PR TITLE
Merge devel into master

### PR DESCRIPTION
**Pull request by amcadmus**

### CODE REVIEW

**Review by AnguseZhang — APPROVED** [review]
Agree with this PR. 

Meanwhile, this PR will introduce a breaking change to DP-GEN, since we will not support python3.7 anymore. So we should release 0.11.0, instead of 0.10.7, shall we?

**Review by njzjz — APPROVED** [review]

**Comment by njzjz** [comment]
> Meanwhile, this PR will introduce a breaking change to DP-GEN, since we will not support python3.7 anymore.

This reminds me to update the documentation in #1060.

**Comment by njzjz** [comment]
warning: #957 has not been fixed yet.

**Comment by amcadmus** [comment]
> Agree with this PR.
> 
> Meanwhile, this PR will introduce a breaking change to DP-GEN, since we will not support python3.7 anymore. So we should release 0.11.0, instead of 0.10.7, shall we?

I agree. it will be released as 0.11.0

**Pull request merged**
