### PR TITLE
fix: remove lmp_traj from forward_files in run_md_model_devi

### PR DESCRIPTION
**Pull request by HuangJiameng**
`lmp_traj` should not be in `forward_files` in `run_model_devi` step.

### CODE REVIEW

**Comment by HuangJiameng** [comment]
This fix aims to solve the problem mentioned in #938.

**Review by wanghan-iapcm — APPROVED** [review]

**Comment by njzjz** [comment]
This PR is incorrect - LAMMPS will throw errors when the directory does not exist.

**Comment by wanghan-iapcm** [comment]
@HuangJiameng have you really tested this PR?

**Comment by HuangJiameng** [comment]
I have tested it with `model_devi_merge_traj = true`. I see, I will fix it.

**Comment by HuangJiameng** [comment]
> This PR is incorrect - LAMMPS will throw errors when the directory does not exist.

This error will occur when `model_devi_merge_traj = false`

**Pull request merged**
