### PR TITLE
Fix the usage of `pair_coeff` in `auto_test`

### PR DESCRIPTION
**Pull request by AnguseZhang**
See https://github.com/deepmodeling/dpgen/pull/567 and https://github.com/deepmodeling/dpgen/issues/697

### CODE REVIEW

**Review by njzjz — CHANGES_REQUESTED** [review]
Please also fix https://github.com/deepmodeling/dpgen/blob/9e3b958e07ebcc1858405daff1033b1a94d88f58/dpgen/auto_test/template/elastic/lmp/potential.mod#L7 and other related codes.

**Comment by AnguseZhang** [comment]
> pair_coeff

Does a normal LAMMPS without DeePMD also require `pair_coeff * *`?

**Comment by njzjz** [comment]
> > pair_coeff
> 
> 
> 
> Does a normal LAMMPS without DeePMD also require `pair_coeff * *`? @njzjz 

I think it't not support any more in a new version of LAMMPS.

**Comment by wanghan-iapcm** [comment]
See also #696

**Pull request merged**
