### PR TITLE
Revert changes to `type_map` and `mass_map`

### PR DESCRIPTION
**Pull request by AnguseZhang**
Since there're still problems with #867, I reverted the previous PR.

### CODE REVIEW

**Comment by panxiang126** [comment]
How about if the mass_type is modified immediately after reading jdata?

`if jdata['mass_map'] == 'auto': jdata['mass_map'] = [get_atomic_masses(i) for i in jdata['type_map']]`

**Comment by panxiang126** [comment]
I do not know how to submit my changes. it seems I have no permission.

**Comment by amcadmus** [comment]
> How about if the mass_type is modified immediately after reading jdata?
> 
> `if jdata['mass_map'] == 'auto': jdata['mass_map'] = [get_atomic_masses(i) for i in jdata['type_map']]`

It is a good idea.

**Comment by wanghan-iapcm** [comment]
> I do not know how to submit my changes. it seems I have no permission.

Sorry it was our problem, the PR #867 was merged without the agreement of all reviewers. Could you please open a new PR to submit your suggested revisions? Thank you very much.

**Comment by wanghan-iapcm** [comment]
> How about if the mass_type is modified immediately after reading jdata?
> 
> `if jdata['mass_map'] == 'auto': jdata['mass_map'] = [get_atomic_masses(i) for i in jdata['type_map']]`

I agree with you.

**Comment by wanghan-iapcm** [comment]
@AnguseZhang Thank you for this reverting PR. 
The way that fixes #867 and bothers @panxiang126 least is to submit the fix as a new PR. What do you think?

**Comment by AnguseZhang** [comment]
> @AnguseZhang Thank you for this reverting PR. The way that fixes #867 and bothers @panxiang126 least is to submit the fix as a new PR. What do you think?

Agree. Shall we merge this PR, and let @panxiang126 submit a new PR ? @wanghan-iapcm

**Comment by AnguseZhang** [comment]
@panxiang126 Sorry for bothering you. Thanks again for your contribution.

**Comment by panxiang126** [comment]
> @panxiang126 Sorry for bothering you. Thanks again for your contribution.

glad to do something for the DP community. I will submit a new PR after this one is merged.

**Review by amcadmus — APPROVED** [review]

**Comment by wanghan-iapcm** [comment]
> > @panxiang126 Sorry for bothering you. Thanks again for your contribution.
> 
> glad to do something for the DP community. I will submit a new PR after this one is merged.

Merged. Please submit the new PR. Thank you very much.

**Pull request merged**
