### PR TITLE
Add a local submission json file with 4-GPU.

### PR DESCRIPTION
**Pull request by Kick-H**

### CODE REVIEW

**Review by AnguseZhang — COMMENTED** [review]
@Kick-H  Hi Kick, thanks for your contributions!   Could you please add some necessary explanations for this example? For example, `maunal_cuda_devices` , `cuda_multi_task` and `group_size` should be carefully designated and are different from a common single-GPU example.  The comments can be added via some different keys,  you can refer to https://github.com/deepmodeling/dpgen/blob/devel/examples/machine/DeePMD-kit-1.x/machine-slurm-qe.json. Thanks again!

**Comment by Kick-H** [comment]
Of course, I will add the comments according to the example later.

**Comment by Kick-H** [comment]
I have conducted a simple test to ensure that all four GPUs are in use. Please check again.

**Review by AnguseZhang — CHANGES_REQUESTED** [review]
I've refined this example in https://github.com/Kick-H/dpgen/pull/1. 
Please merge this into your branch. 
No other problems/suggestions. Thanks!

**Comment by Kick-H** [comment]
Thanks for your revision. @AnguseZhang

**Comment by amcadmus** [comment]
Lack of response. 

We have to start anther PR to incorporate the changes in PR https://github.com/Kick-H/dpgen/pull/1

**Pull request merged**
