### PR TITLE
doc: dpgen run machine parameters

### PR DESCRIPTION
**Pull request by njzjz**

### CODE REVIEW

**Comment by njzjz** [comment]
What's wrong with the UT?

**Comment by AnguseZhang** [comment]
> What's wrong with the UT?

[dpdata 0.2.6](https://github.com/deepmodeling/dpdata/releases/tag/0.2.6) has not supported for older version than 2.2. So UT in DP-GEN also fails. @Liu-RX Could you please fix UT in `DP-GEN`?

**Comment by Liu-RX** [comment]
> > What's wrong with the UT?
> 
> [dpdata 0.2.6](https://github.com/deepmodeling/dpdata/releases/tag/0.2.6) has not supported for older version than 2.2. So UT in DP-GEN also fails. @Liu-RX Could you please fix UT in `DP-GEN`?

I have fixed it in #705. But I haven't fulfill your review requirements. I will do it as soon as possible.

**Comment by AnguseZhang** [comment]
> > > What's wrong with the UT?
> > 
> > 
> > [dpdata 0.2.6](https://github.com/deepmodeling/dpdata/releases/tag/0.2.6) has not supported for older version than 2.2. So UT in DP-GEN also fails. @Liu-RX Could you please fix UT in `DP-GEN`?
> 
> I have fixed it in #705. But I haven't fulfill your review requirements. I will do it as soon as possible.

Ok. Thanks !

**Comment by njzjz** [comment]
@AnguseZhang could you enable the PR preview in read the docs?
image

**Comment by AnguseZhang** [comment]
> @AnguseZhang could you enable the PR preview in read the docs? image

Yes @njzjz  I've done. Does it work?

**Comment by njzjz** [comment]
> > @AnguseZhang could you enable the PR preview in read the docs? image
> 
> 
> 
> Yes @njzjz  I've done. Does it work?

It should work: https://deepmodeling--710.org.readthedocs.build/projects/dpgen/en/710/run-mdata.html

**Review by AnguseZhang — APPROVED** [review]

**Pull request merged**
