### PR TITLE
add amber model_devi_engine and amber/corr fp_style

### PR DESCRIPTION
**Pull request by njzjz**
~(and make the code more like a 💩 hill)~

TODO: add an unittest

### CODE REVIEW

**Comment by AnguseZhang** [comment]
Got. I may review this on Wed/Thur.

**Review by AnguseZhang — COMMENTED** [review]
My concern is that both this commit for Amber and my last commit for Gromacs are so specific that no one else can use these functions. Do you think that we should support more general cases, just like CH4, and make this as a milestone for a PR?

**Comment by njzjz** [comment]
> My concern is that both this commit for Amber and my last commit for Gromacs are so specific that no one else can use these functions. Do you think that we should support more general cases, just like CH4, and make this as a milestone for a PR?

What I suggest is to make DP-GEN support plugins... but it may take a lot of effort. If someone else also has this idea, we can implement it together.

**Comment by AnguseZhang** [comment]
> > My concern is that both this commit for Amber and my last commit for Gromacs are so specific that no one else can use these functions. Do you think that we should support more general cases, just like CH4, and make this as a milestone for a PR?
> 
> What I suggest is to make DP-GEN support plugins... but it may take a lot of effort. If someone else also has this idea, we can implement it together.

What do you meany by supporting plugins? Is there an example? I don't think plugin like plumed is similar to DP-GEN.

**Comment by njzjz** [comment]
> > > My concern is that both this commit for Amber and my last commit for Gromacs are so specific that no one else can use these functions. Do you think that we should support more general cases, just like CH4, and make this as a milestone for a PR?
> > 
> > 
> > What I suggest is to make DP-GEN support plugins... but it may take a lot of effort. If someone else also has this idea, we can implement it together.
> 
> What do you meany by supporting plugins? Is there an example? I don't think plugin like plumed is similar to DP-GEN.

Like LAMMPS? In a LAMMPS plugin, one can add custom `fix` and `pair` styles by define a new class (e.g. [deepmd's LAMMPS plugin](https://github.com/deepmodeling/deepmd-kit/blob/afc557abcf17eb7d37f2bf93624fc060122dc241/source/lmp/pair_deepmd.cpp#L232-L233)). For DP-GEN, `model_devi` and `fp` styles can also be customize.

**Comment by AnguseZhang** [comment]
> > > > My concern is that both this commit for Amber and my last commit for Gromacs are so specific that no one else can use these functions. Do you think that we should support more general cases, just like CH4, and make this as a milestone for a PR?
> > > 
> > > 
> > > What I suggest is to make DP-GEN support plugins... but it may take a lot of effort. If someone else also has this idea, we can implement it together.
> > 
> > 
> > What do you meany by supporting plugins? Is there an example? I don't think plugin like plumed is similar to DP-GEN.
> 
> Like LAMMPS? In a LAMMPS plugin, one can add custom `fix` and `pair` styles by define a new class (e.g. [deepmd's LAMMPS plugin](https://github.com/deepmodeling/deepmd-kit/blob/afc557abcf17eb7d37f2bf93624fc060122dc241/source/lmp/pair_deepmd.cpp#L232-L233)). In DP-GEN, `model_devi` and `fp` styles can also be customize.

This is gonna like refacting DP-GEN codes,  I talked with @amcadmus and came to conclusion that it's necessary but we don't have time for now.  Ok let's go back to this PR. I try to be more specfic.  Recall that when previously other developers implement a new fp style, like PWMAT, SIESTA, CP2K, e.t.c, their milestone is to use DP-GEN to run a complete case where fp calculation method is replaced wtih the new method. So I think if we add a new model_devi engine,like Gromacs and Amber, the same milestone should be applied. Otherwise, we cannot tell someone else who is interested in trying DP-GEN with Gromacs and Amber  how to use.

**Comment by njzjz** [comment]
Do you mean it should be possible to mix any `model_devi_engine` and any `fp_style`? Err I think it's a bit hard to do so if we don't refactor codes, as there is too much thing coupling here. For example, the output of `model_devi` is used to start `fp_style`, and we should first define an unified input and output for decoupling.

**Comment by njzjz** [comment]
In my idea, currently a part of `make_fp` is actually the post-processing of `model_devi` and needs to move to `post_model_devi`. 
https://github.com/deepmodeling/dpgen/blob/e89d7fc67e59bccadfc93cc3f12d8b205333d6fc/dpgen/generator/run.py#L1272

And also, it's very strange here to switch `model_devi_engine` in a `fp` function. The output of `model_devi` should be unified to be used by `fp`.
https://github.com/deepmodeling/dpgen/blob/e89d7fc67e59bccadfc93cc3f12d8b205333d6fc/dpgen/generator/run.py#L1878-L1883

**Comment by AnguseZhang** [comment]
> Do you mean it should be possible to mix any `model_devi_engine` and any `fp_style`? Err I think it's a bit hard to do so if we don't refactor codes, as there is too much thing coupling here. For example, the output of `model_devi` is used to start `fp_style`, and we should first define an unified input and output for decoupling.

I think this is the second stage. The first stage is to successfully run an easy and general case in Amber or Gromacs, and provide examples `param.json`.

**Comment by AnguseZhang** [comment]
> In my idea, currently a part of `make_fp` is actually the post-processing of `model_devi` and needs to move to `post_model_devi`.
> https://github.com/deepmodeling/dpgen/blob/e89d7fc67e59bccadfc93cc3f12d8b205333d6fc/dpgen/generator/run.py#L1272
> 
> And also, it's very strange here to switch `model_devi_engine` in a `fp` function. The output of `model_devi` should be unified to be used by `fp`.
> https://github.com/deepmodeling/dpgen/blob/e89d7fc67e59bccadfc93cc3f12d8b205333d6fc/dpgen/generator/run.py#L1878-L1883

I argee.

**Pull request closed without merging**
