### PR TITLE
add another check_status option for psate (PBS)

### PR DESCRIPTION
**Pull request by Manyi-Yang**
fix the bug posted on:
https://github.com/deepmodeling/dpgen/issues/395

### CODE REVIEW

**Review by njzjz — APPROVED** [review]
This is what I suggested Manyi.

**Review by AnguseZhang — APPROVED** [review]
There's no problem. @felix5572  Please see this, dpdispatcher would also need this.

**Comment by AnguseZhang** [comment]
@Manyi-Yang  Hi, Manyi. I noticed the branch of your PR is based on "master" branch. However, master branch serves as a  currently stable version of codes for users and developers should first pull the latest codes on "devel" branch and commit their changes to "devel" branch.  Could you please modify your commits ? Thanks!

Yuzhi

**Comment by felix5572** [comment]
ok I will write down this in an issue

**Comment by amcadmus** [comment]
Merged thank you!

**Pull request merged**
