### PR TITLE
add simplify workflow

### PR DESCRIPTION
**Pull request by njzjz**
Simplify the given dataset.
```bash
dpgen simplify param.json machine.json
```
An example for `param.json` (just for test):
```json
{
    "type_map": [
        "C",
        "H",
        "N",
        "O",
        "S"
    ],
    "mass_map": [
        12.011,
        1.008,
        14.007,
        15.999,
        32.065
    ],
    "pick_data": "/scratch/jz748/simplify/qm7",
    "init_data_prefix": "",
    "init_data_sys": [],
    "sys_batch_size": [
        "auto"
    ],
    "numb_models": 4,
    "train_param": "input.json",
    "default_training_param": {
        "model": {
            "type_map": [
                "C",
                "H",
                "N",
                "O",
                "S"
            ],
            "descriptor": {
                "type": "se_a",
                "sel": [
                    7,
                    16,
                    3,
                    3,
                    1
                ],
                "rcut_smth": 1.00,
                "rcut": 6.00,
                "neuron": [
                    25,
                    50,
                    100
                ],
                "resnet_dt": false,
                "axis_neuron": 12
            },
            "fitting_net": {
                "neuron": [
                    240,
                    240,
                    240
                ],
                "resnet_dt": true
            }
        },
        "learning_rate": {
            "type": "exp",
            "start_lr": 0.001,
            "decay_steps": 10,
            "decay_rate": 0.99
        },
        "loss": {
            "start_pref_e": 0.02,
            "limit_pref_e": 1,
            "start_pref_f": 1000,
            "limit_pref_f": 1,
            "start_pref_v": 0,
            "limit_pref_v": 0,
            "start_pref_pf": 0,
            "limit_pref_pf": 0
        },
        "training": {
            "set_prefix": "set",
            "stop_batch": 10000,
            "disp_file": "lcurve.out",
            "disp_freq": 1000,
            "numb_test": 1,
            "save_freq": 1000,
            "save_ckpt": "model.ckpt",
            "load_ckpt": "model.ckpt",
            "disp_training": true,
            "time_training": true,
            "profiling": false,
            "profiling_file": "timeline.json"
        },
        "_comment": "that's all"
    },
    "use_clusters": true,
    "fp_style": "gaussian",
    "shuffle_poscar": false,
    "fp_task_max": 1000,
    "fp_task_min": 10,
    "fp_pp_path": "/home/jzzeng/",
    "fp_pp_files": [],
    "fp_params": {
        "keywords": "mn15/6-31g** force nosymm scf(maxcyc=512)",
        "nproc": 28,
        "multiplicity": 1,
        "_comment": " that's all "
    },
    "init_pick_number":100,
    "iter_pick_number":100,
    "e_trust_lo":1e10,
    "e_trust_hi":1e10,
    "f_trust_lo":0.25,
    "f_trust_hi":0.45,
    "_comment": " that's all "
}
```
Here some parameters are the same as those of generator. `pick_data` is the data to simplify (maybe can have a better name) and currently only supports `MultiSystems` containing `System` with `deepmd/npy` format (so `use_clusters` should be `true`). `init_pick_number` and `iter_pick_number` are the number of picked frames. `f_trust_lo` and `f_trust_hi` means the max deviation of atomic forces in a frame. `fp_style` can be `gaussian` currently.

Here is `machine.json`:
```json
{
    "python_path":  "/home/jz748/anaconda3/envs/deepmd/bin/python",
    "train_machine":    {
    "machine_type": "slurm",
    "hostname" :    "localhost",
    "port" :    22,
    "username": "jz748",
    "work_path" :   "/scratch/jz748/dpgen_workdir",
    "_comment" :    "that's all"
    },
    "train_resources":  {
    "numb_node": 1,
    "task_per_node": 3,
    "partition": "gpu",
    "job_name": "dpgen_jzzeng",
    "with_mpi": false,
    "time_limit": "72:00:00",
    "numb_gpu": 1,
    "exclude_list": ["gpu001", "gpu003", "gpu006"],
    "_comment": "that's all"
    },

    "model_devi_group_size":    20,
    "model_devi_machine":   {
    "machine_type": "slurm",
    "hostname" :    "localhost",
    "port" :    22,
    "username": "jz748",
    "work_path" :   "/scratch/jz748/dpgen_workdir",
    "_comment" :    "that's all"
    },
    "model_devi_resources": {
    "numb_node": 1,
    "task_per_node": 3,
    "partition": "gpu",
    "job_name": "dpgen_jzzeng",
    "with_mpi": false,
    "time_limit": "72:00:00",
    "numb_gpu": 1,
    "exclude_list": ["gpu001", "gpu003", "gpu006"],
    "_comment": "that's all"
    },

    "_comment":     "fp on lsf //localhost ",
    "fp_command":   "g16 < input",
    "fp_group_size":    20,
    "fp_machine":   {
    "machine_type": "slurm",
    "hostname" :    "localhost",
    "port" :    22,
    "username": "jz748",
    "work_path" :   "/scratch/jz748/dpgen_workdir",
    "_comment" :    "that's all"
    },
    "fp_resources": {
    "module_list": ["gaussian/16revA03"],
    "numb_node": 1,
    "job_name": "dpgen_jzzeng",
    "task_per_node": 28,
    "with_mpi": false,
    "time_limit": 360,
    "allow_failure": true,
    "partition": "main",
    "_comment": "that's all"
    },
    "_comment":     " that's all "
}
```

In order to test the program, I simplify QM7 dataset, which can be [obtained here](https://github.com/njzjz/kcon/blob/jctc/datasets/qm7.xyz?raw=true) and converted to `deepmd/npy` with the following script:
```python
import dpdata
import numpy as np

sys=dpdata.MultiSystems()
i = 0
with open("qm7.xyz") as f:
    for line in f:
        if i == 0:
            i += int(line)+1
            crd=[]
            sym=[]
        else:
            i -= 1
            s = line.split()
            if len(s)==4:
                sym.append(s[0])
                crd.append(list(map(float,s[1:])))
            if i == 0:
                s=dpdata.System()
                s.data['coords']=np.array([crd])
                s.data['cells']=np.array([[[100,0,0],[0,100,0],[0,0,100]]])
                atom_names, s.data['atom_types'], atom_numbs = np.unique(sym, return_inverse=True, return_counts=True)
                s.data['atom_names'] = list(atom_names)
                s.data['atom_numbs'] = list(atom_numbs)
                sys.append(s)
print(sys)
sys.to_deepmd_npy("qm7")
```

### CODE REVIEW

**Comment by njzjz** [comment]
## QM7
set f_low and f_high to 0.25 eV/A and 0.45 eV/A (just for test, maybe a bit high)
**iter.000000:**
pick 100 frames from 7165
**iter.000001:**
candidate :   2020 in   7065  28.59 % (pick 100 from here)
accurate  :   4722 in   7065  66.84 % (won't test again)
failed    :    323 in   7065   4.57 %
**iter.000002:**
candidate :    683 in   2245  30.42 % (pick 100 from here)
accurate  :   1405 in   2245  62.58 % (won't test again)
failed    :    157 in   2245   6.99 %
**iter.000003:**

**Comment by amcadmus** [comment]
Please update the readme by the instructions provided with this PR

**Comment by njzjz** [comment]
The document has been added, and note that deepmodeling/dpdata#64 should be merged to make sure the program runs successfully.

**Comment by njzjz** [comment]
deepmodeling/dpdata#55 seems to cause the CI fails?

**Pull request merged**
