### PR TITLE
gamma line calculation for bcc and fcc

### PR DESCRIPTION
**Pull request by kevinwenminion**
1. add gamma line calculation for bcc and fcc.

2. should be no problem for bcc {110}, {112}, and {123} planes along <111>/2 direction; fcc {111} plane along <1-10>/2 and <11-2>/2 directions.

### CODE REVIEW

**Review by wanghan-iapcm — APPROVED** [review]

**Comment by Vibsteamer** [comment]
Dear contributors,
There are five points maybe needed for further consideration:
1. `dpgen/auto_test/Gamma.py`, the "min" in the key of parameters "min_super_cell_size" seems not intuitive, which key just refers to the replication times in three dimensions of the super-cell with respect to the primitive cell. (had communicated with the contributor)
2.  `dpgen/auto_test/Gamma.py`, the function `__gen_slab_pmg` is defined but is not called elsewhere, seem to be a dangling function for the time being. If it is prepared for further developments in future pr, adding some comments maybe more friendly to other developers/code_readers. 
3. `POTCAR` files should bot be uploaded for copyrights limitation
4. for giving the example and unitest, Maybe `OUTCAR` files could be uploaded instead, and corresponding test of `post` process could be added into the unitest.
5. `dpgen/auto_test/Lammps.py`, the default convergence criteria for lammps tasks are changed into force-dependent-only, which may influence all other properties in auto-test. Please add a comment explaining the consideration of this revise.

**Review by Vibsteamer — COMMENTED** [review]
Dear contributors,
There are five points maybe needed for further consideration:

1.`dpgen/auto_test/Gamma.py`, the "min" in the key of parameters "min_super_cell_size" seems not intuitive, which key just refers to the replication times in three dimensions of the super-cell with respect to the primitive cell. (had communicated with the contributor)
2.`dpgen/auto_test/Gamma.py`, the function `__gen_slab_pmg` is defined but is not called elsewhere, seem to be a dangling function for the time being. If it is prepared for further developments in future pr, adding some comments maybe more friendly to other developers/code_readers.
3.`POTCAR` files should bot be uploaded for copyrights limitation
4.for giving the example and unitest, Maybe `OUTCAR` files could be uploaded instead, and corresponding test of post process could be added into the unitest.
5.`dpgen/auto_test/Lammps.py`, the default convergence criteria for lammps tasks are changed into force-dependent-only, which may influence all other properties in auto-test. Please add a comment explaining the consideration of this revise.

**Comment by wanghan-iapcm** [comment]
Please checkout a new branch and make a new PR for the cohesive energy line. @kevinwenminion

**Comment by kevinwenminion** [comment]
Dear reviewers,

Problems 1-4 have been solved and the unitest for gamma-line post for lmp calculation has been added.

For the last question, when relaxing the supercell with many atoms, force convergence is much more robust than energy convergence. From our experience, the force convergence of 1e-10 for DP should be OK in most situations.

Thanks a lot for your careful review and time.

**Comment by AnguseZhang** [comment]
Thanks for the contributions!  But there're so many output files, are they necessary?

**Review by Vibsteamer — APPROVED** [review]

**Pull request merged**
