### PR TITLE
extend the doc of cp2k external_input_path in detail

### PR DESCRIPTION
**Pull request by robinzyb**
How to add code blocks in the doc?

### CODE REVIEW

**Comment by njzjz** [comment]
> How to add code blocks in the doc?

It's generated in the RST file so that you can follow the RST grammar. https://devguide.python.org/documentation/markup/

**Comment by robinzyb** [comment]
why did CI fail at `TypeError: issubclass() arg 1 must be a class` ?  I make no change on this part of test code

**Comment by njzjz** [comment]
> why did CI fail at `TypeError: issubclass() arg 1 must be a class` ? I make no change on this part of test code

I can reproduce the error in a clean python 3.8 image.

**Comment by njzjz** [comment]
I submit https://github.com/materialsproject/pymatgen/issues/3009 to pymatgen and hope this issue can be resolved as soon as possible.

**Pull request merged**
