### PR TITLE
generate run arg doc from scripts

### PR DESCRIPTION
**Pull request by njzjz**
This commit generates run argument documentation from scripts (inited by @LiangWenshuo1118) at runtime, so we can work together on the script to improve the docs.

I see some arguments are still missing here...

### CODE REVIEW

**Review by AnguseZhang — COMMENTED** [review]
@njzjz Great work! @LiangWenshuo1118 Please help check.

**Review by wanghan-iapcm — APPROVED** [review]

**Comment by njzjz** [comment]
Removed `init_multi_systems` considering #730 has been merged.

**Comment by njzjz** [comment]
Switched to new dargs directive.

**Comment by njzjz** [comment]
The following is missing:

- training
  - [ ] training_reuse_iter
  - [ ] training_reuse_old_ratio
  - [ ] training_reuse_stop_batch
  - [ ] training_reuse_numb_steps
  - [ ] training_reuse_start_lr
  - [ ] training_reuse_start_pref_e
  - [ ] training_reuse_start_pref_f
- model devi
  - [ ] gromacs
  - [ ] amber
  - [ ] calypso
  - [ ] revise_template
  - [ ] buffet
- fp
  - [ ] pwmat
  - [ ] abacus
  - [ ] amber/diff
  - [ ] some parameters of gaussian

**Review by HuangJiameng — APPROVED** [review]

**Pull request merged**
